import { Exercise } from './types';

export const exercisesDatabase: Exercise[] = [

  // ── MUSCULATION SANS MACHINE (Poids du corps) ────────────────────────────

  { id: 'bw-01', name: 'Pompes classiques', category: 'musculation', equipment: ['aucun'], muscles: ['pectoraux'], muscleSecondary: ['triceps', 'epaules'], difficulty: 'debutant', description: 'Position planche, mains à largeur d\'épaules, descendre la poitrine vers le sol puis repousser.', tips: 'Gardez le gainage actif, ne laissez pas les hanches tomber.', defaultSets: 3, defaultReps: '12-15', defaultRest: 60 },
  { id: 'bw-02', name: 'Pompes diamant', category: 'musculation', equipment: ['aucun'], muscles: ['triceps'], muscleSecondary: ['pectoraux', 'epaules'], difficulty: 'intermediaire', description: 'Mains rapprochées en triangle sous la poitrine, coudes le long du corps.', tips: 'Idéal pour isoler les triceps. Descente lente.', defaultSets: 3, defaultReps: '10-12', defaultRest: 60 },
  { id: 'bw-03', name: 'Pompes larges', category: 'musculation', equipment: ['aucun'], muscles: ['pectoraux'], muscleSecondary: ['epaules'], difficulty: 'debutant', description: 'Mains plus larges que les épaules, stretch pectoral prononcé en bas.', defaultSets: 3, defaultReps: '10-15', defaultRest: 60 },
  { id: 'bw-04', name: 'Pompes déclinées', category: 'musculation', equipment: ['aucun', 'banc'], muscles: ['pectoraux'], muscleSecondary: ['triceps', 'epaules'], difficulty: 'intermediaire', description: 'Pieds surélevés sur un banc ou une chaise, accent sur le haut des pectoraux.', defaultSets: 3, defaultReps: '10-12', defaultRest: 60 },
  { id: 'bw-05', name: 'Pompes inclinées', category: 'musculation', equipment: ['aucun', 'banc'], muscles: ['pectoraux'], muscleSecondary: ['triceps'], difficulty: 'debutant', description: 'Mains sur un banc élevé, corps incliné. Plus facile, idéal pour débutants.', defaultSets: 3, defaultReps: '15-20', defaultRest: 45 },
  { id: 'bw-06', name: 'Traction prise large', category: 'musculation', equipment: ['barre_traction'], muscles: ['dos'], muscleSecondary: ['biceps', 'epaules'], difficulty: 'intermediaire', description: 'Barre en pronation, prise large, tirer jusqu\'au menton au-dessus de la barre.', tips: 'Ne balancez pas le corps, engagement des omoplates.', defaultSets: 3, defaultReps: '6-10', defaultRest: 90 },
  { id: 'bw-07', name: 'Traction prise serrée (Chin-up)', category: 'musculation', equipment: ['barre_traction'], muscles: ['biceps'], muscleSecondary: ['dos'], difficulty: 'intermediaire', description: 'Prise en supination (paumes vers vous), bras serrés. Accent sur les biceps.', defaultSets: 3, defaultReps: '6-10', defaultRest: 90 },
  { id: 'bw-08', name: 'Squat poids du corps', category: 'musculation', equipment: ['aucun'], muscles: ['quadriceps'], muscleSecondary: ['fessiers', 'ischio_jambiers'], difficulty: 'debutant', description: 'Pieds à largeur d\'épaules, descendre jusqu\'aux cuisses parallèles au sol.', tips: 'Genoux dans l\'axe des orteils, talon au sol.', defaultSets: 3, defaultReps: '15-20', defaultRest: 60 },
  { id: 'bw-09', name: 'Squat sauté', category: 'musculation', equipment: ['aucun'], muscles: ['quadriceps'], muscleSecondary: ['fessiers', 'mollets'], difficulty: 'intermediaire', description: 'Squat classique avec saut explosif en haut, atterrissage doux.', defaultSets: 3, defaultReps: '10-15', defaultRest: 60 },
  { id: 'bw-10', name: 'Fente avant', category: 'musculation', equipment: ['aucun'], muscles: ['quadriceps'], muscleSecondary: ['fessiers', 'ischio_jambiers'], difficulty: 'debutant', description: 'Un pied en avant, genou arrière proche du sol. Alterner les jambes.', tips: 'Genou avant ne dépasse pas le bout du pied.', defaultSets: 3, defaultReps: '12 par jambe', defaultRest: 60 },
  { id: 'bw-11', name: 'Fente arrière', category: 'musculation', equipment: ['aucun'], muscles: ['quadriceps'], muscleSecondary: ['fessiers'], difficulty: 'debutant', description: 'Pied arrière reculé, genou arrière vers le sol. Plus stable que la fente avant.', defaultSets: 3, defaultReps: '12 par jambe', defaultRest: 60 },
  { id: 'bw-12', name: 'Fente latérale', category: 'musculation', equipment: ['aucun'], muscles: ['quadriceps'], muscleSecondary: ['fessiers', 'ischio_jambiers'], difficulty: 'intermediaire', description: 'Pas latéral large, fléchir une jambe tout en gardant l\'autre tendue.', defaultSets: 3, defaultReps: '10 par jambe', defaultRest: 60 },
  { id: 'bw-13', name: 'Pont fessier', category: 'musculation', equipment: ['aucun', 'tapis'], muscles: ['fessiers'], muscleSecondary: ['ischio_jambiers', 'abdominaux'], difficulty: 'debutant', description: 'Allongé sur le dos, pieds à plat, soulever le bassin en contractant les fessiers.', tips: 'Tenir 2s en haut pour maximiser la contraction.', defaultSets: 3, defaultReps: '15-20', defaultRest: 45 },
  { id: 'bw-14', name: 'Hip thrust (poids du corps)', category: 'musculation', equipment: ['aucun', 'banc'], muscles: ['fessiers'], muscleSecondary: ['ischio_jambiers'], difficulty: 'debutant', description: 'Dos appuyé sur un banc, bassin au sol, pousser les hanches vers le haut.', defaultSets: 3, defaultReps: '15-20', defaultRest: 60 },
  { id: 'bw-15', name: 'Dips (chaise)', category: 'musculation', equipment: ['aucun', 'banc'], muscles: ['triceps'], muscleSecondary: ['pectoraux', 'epaules'], difficulty: 'debutant', description: 'Mains sur le bord d\'une chaise, descendre le corps en fléchissant les coudes.', defaultSets: 3, defaultReps: '12-15', defaultRest: 60 },
  { id: 'bw-16', name: 'Planche avant', category: 'musculation', equipment: ['aucun', 'tapis'], muscles: ['gainage'], muscleSecondary: ['abdominaux', 'epaules'], difficulty: 'debutant', description: 'Position planche sur les avant-bras ou mains, corps aligné, tenir la position.', defaultSets: 3, defaultDuration: '30-60s', defaultRest: 45 },
  { id: 'bw-17', name: 'Planche latérale', category: 'musculation', equipment: ['aucun', 'tapis'], muscles: ['obliques'], muscleSecondary: ['gainage', 'epaules'], difficulty: 'intermediaire', description: 'Appui sur un avant-bras, corps en ligne droite, hanches levées.', defaultSets: 3, defaultDuration: '20-45s par côté', defaultRest: 45 },
  { id: 'bw-18', name: 'Crunch', category: 'musculation', equipment: ['aucun', 'tapis'], muscles: ['abdominaux'], difficulty: 'debutant', description: 'Sur le dos, genoux fléchis, relever les épaules en contractant les abdos.', defaultSets: 3, defaultReps: '20', defaultRest: 45 },
  { id: 'bw-19', name: 'Relevé de jambes suspendu', category: 'musculation', equipment: ['barre_traction'], muscles: ['abdominaux'], muscleSecondary: ['obliques'], difficulty: 'avance', description: 'Suspendu à une barre, relever les jambes tendues jusqu\'à la barre.', defaultSets: 3, defaultReps: '10-12', defaultRest: 60 },
  { id: 'bw-20', name: 'Mountain climbers', category: 'musculation', equipment: ['aucun', 'tapis'], muscles: ['abdominaux'], muscleSecondary: ['epaules', 'quadriceps'], difficulty: 'intermediaire', description: 'Position pompes, ramener les genoux alternativement vers la poitrine rapidement.', defaultSets: 3, defaultDuration: '30s', defaultRest: 45 },
  { id: 'bw-21', name: 'Superman', category: 'musculation', equipment: ['aucun', 'tapis'], muscles: ['dos'], muscleSecondary: ['fessiers', 'ischio_jambiers'], difficulty: 'debutant', description: 'À plat ventre, soulever bras et jambes simultanément en contractant le bas du dos.', defaultSets: 3, defaultReps: '15', defaultRest: 45 },
  { id: 'bw-22', name: 'Élévation des mollets', category: 'musculation', equipment: ['aucun'], muscles: ['mollets'], difficulty: 'debutant', description: 'Debout, se mettre sur la pointe des pieds lentement, descendre contrôlé.', defaultSets: 4, defaultReps: '20-25', defaultRest: 45 },
  { id: 'bw-23', name: 'Pistol squat', category: 'musculation', equipment: ['aucun'], muscles: ['quadriceps'], muscleSecondary: ['fessiers', 'gainage'], difficulty: 'avance', description: 'Squat sur une seule jambe, autre jambe tendue devant soi.', tips: 'Commencer avec assistance (TRX ou chaise) pour les débutants.', defaultSets: 3, defaultReps: '5-8 par jambe', defaultRest: 90 },
  { id: 'bw-24', name: 'Burpees', category: 'musculation', equipment: ['aucun'], muscles: ['corps_entier'], difficulty: 'intermediaire', description: 'Squat → pompe → saut. Mouvement complet full body à haute intensité.', defaultSets: 3, defaultReps: '10', defaultRest: 60 },
  { id: 'bw-25', name: 'Pike push-up', category: 'musculation', equipment: ['aucun'], muscles: ['epaules'], muscleSecondary: ['triceps'], difficulty: 'intermediaire', description: 'Position en V inversé, plier les coudes pour amener la tête vers le sol.', defaultSets: 3, defaultReps: '10-12', defaultRest: 60 },

  // ── MUSCULATION AVEC HALTÈRES ─────────────────────────────────────────────

  { id: 'db-01', name: 'Développé couché haltères', category: 'musculation', equipment: ['halteres', 'banc'], muscles: ['pectoraux'], muscleSecondary: ['triceps', 'epaules'], difficulty: 'debutant', description: 'Allongé sur un banc, haltères de chaque côté de la poitrine, pousser vers le haut.', tips: 'Descendre lentement, coudes à 45° du corps.', defaultSets: 4, defaultReps: '10-12', defaultRest: 90 },
  { id: 'db-02', name: 'Écarté couché haltères', category: 'musculation', equipment: ['halteres', 'banc'], muscles: ['pectoraux'], difficulty: 'intermediaire', description: 'Bras tendus, ouvrir en arc de cercle vers les côtés, sentir le stretch pectoral.', defaultSets: 3, defaultReps: '12-15', defaultRest: 75 },
  { id: 'db-03', name: 'Rowing haltère', category: 'musculation', equipment: ['halteres', 'banc'], muscles: ['dos'], muscleSecondary: ['biceps', 'epaules'], difficulty: 'debutant', description: 'Genou et main sur le banc, tirer l\'haltère vers la hanche en gardant le dos droit.', tips: 'Initier le mouvement avec le coude, pas la main.', defaultSets: 4, defaultReps: '10-12', defaultRest: 75 },
  { id: 'db-04', name: 'Curl biceps haltères', category: 'musculation', equipment: ['halteres'], muscles: ['biceps'], muscleSecondary: ['avant_bras'], difficulty: 'debutant', description: 'Debout ou assis, fléchir les avant-bras vers les épaules alternativement ou simultanément.', defaultSets: 3, defaultReps: '12', defaultRest: 60 },
  { id: 'db-05', name: 'Curl marteau', category: 'musculation', equipment: ['halteres'], muscles: ['biceps'], muscleSecondary: ['avant_bras'], difficulty: 'debutant', description: 'Curl avec prise neutre (pouce vers le haut), recrute le brachio-radial.', defaultSets: 3, defaultReps: '12', defaultRest: 60 },
  { id: 'db-06', name: 'Extension triceps couché haltère', category: 'musculation', equipment: ['halteres', 'banc'], muscles: ['triceps'], difficulty: 'debutant', description: 'Allongé, haltère au-dessus de la tête, plier les coudes pour descendre derrière la tête.', defaultSets: 3, defaultReps: '12', defaultRest: 60 },
  { id: 'db-07', name: 'Développé militaire haltères', category: 'musculation', equipment: ['halteres'], muscles: ['epaules'], muscleSecondary: ['triceps'], difficulty: 'debutant', description: 'Assis ou debout, haltères à hauteur des épaules, pousser vers le haut.', defaultSets: 4, defaultReps: '10-12', defaultRest: 75 },
  { id: 'db-08', name: 'Élévations latérales', category: 'musculation', equipment: ['halteres'], muscles: ['epaules'], difficulty: 'debutant', description: 'Bras légèrement fléchis, lever les haltères latéralement jusqu\'à hauteur des épaules.', tips: 'Ne jamais dépasser l\'horizontale, charge légère.', defaultSets: 3, defaultReps: '15', defaultRest: 60 },
  { id: 'db-09', name: 'Élévations frontales', category: 'musculation', equipment: ['halteres'], muscles: ['epaules'], difficulty: 'debutant', description: 'Lever les haltères devant soi, prise pronation ou neutre.', defaultSets: 3, defaultReps: '12', defaultRest: 60 },
  { id: 'db-10', name: 'Oiseau (élévations postérieures)', category: 'musculation', equipment: ['halteres'], muscles: ['epaules'], muscleSecondary: ['dos'], difficulty: 'intermediaire', description: 'Penché à 45°, bras tendus, lever les haltères sur les côtés. Travaille les deltoïdes postérieurs.', defaultSets: 3, defaultReps: '15', defaultRest: 60 },
  { id: 'db-11', name: 'Squat goblet', category: 'musculation', equipment: ['halteres', 'kettlebell'], muscles: ['quadriceps'], muscleSecondary: ['fessiers', 'abdominaux'], difficulty: 'debutant', description: 'Haltère ou kettlebell tenu contre la poitrine, squat profond en gardant le dos droit.', defaultSets: 4, defaultReps: '12-15', defaultRest: 75 },
  { id: 'db-12', name: 'Hip thrust haltères', category: 'musculation', equipment: ['halteres', 'banc'], muscles: ['fessiers'], muscleSecondary: ['ischio_jambiers'], difficulty: 'intermediaire', description: 'Dos sur le banc, haltère sur les hanches, pousser les hanches vers le haut.', tips: 'L\'un des meilleurs exercices pour les fessiers.', defaultSets: 4, defaultReps: '12', defaultRest: 75 },
  { id: 'db-13', name: 'Soulevé de terre haltères (Romanian)', category: 'musculation', equipment: ['halteres'], muscles: ['ischio_jambiers'], muscleSecondary: ['fessiers', 'dos'], difficulty: 'intermediaire', description: 'Jambes quasi tendues, descendre les haltères le long des jambes en poussant les hanches arrière.', defaultSets: 4, defaultReps: '10-12', defaultRest: 90 },
  { id: 'db-14', name: 'Shrugs haltères', category: 'musculation', equipment: ['halteres'], muscles: ['dos'], muscleSecondary: ['epaules'], difficulty: 'debutant', description: 'Haltères sur les côtés, hausser les épaules en contractant les trapèzes.', defaultSets: 3, defaultReps: '15-20', defaultRest: 60 },
  { id: 'db-15', name: 'Swing kettlebell', category: 'musculation', equipment: ['kettlebell'], muscles: ['fessiers'], muscleSecondary: ['ischio_jambiers', 'dos', 'abdominaux'], difficulty: 'intermediaire', description: 'Hanches comme moteur, balance le kettlebell de l\'entrejambe à hauteur des yeux.', tips: 'Mouvement de hip hinge, pas un squat.', defaultSets: 3, defaultReps: '15-20', defaultRest: 60 },

  // ── MUSCULATION AVEC BARRE ────────────────────────────────────────────────

  { id: 'bar-01', name: 'Développé couché barre', category: 'musculation', equipment: ['barre', 'banc'], muscles: ['pectoraux'], muscleSecondary: ['triceps', 'epaules'], difficulty: 'intermediaire', description: 'Barre à largeur d\'épaules, descendre à la poitrine, pousser en arc vers le rack.', tips: 'Pied au sol, dos légèrement arqué, omoplates rétractées.', defaultSets: 4, defaultReps: '5-8', defaultRest: 120 },
  { id: 'bar-02', name: 'Squat barre (back squat)', category: 'musculation', equipment: ['barre'], muscles: ['quadriceps'], muscleSecondary: ['fessiers', 'ischio_jambiers', 'dos'], difficulty: 'intermediaire', description: 'Barre sur les trapèzes, descendre profond, cuisses parallèles minimum.', tips: 'Genou dans l\'axe des orteils, regard légèrement vers le haut.', defaultSets: 4, defaultReps: '5-8', defaultRest: 120 },
  { id: 'bar-03', name: 'Soulevé de terre barre', category: 'musculation', equipment: ['barre'], muscles: ['dos'], muscleSecondary: ['ischio_jambiers', 'fessiers', 'quadriceps'], difficulty: 'avance', description: 'Barre au sol, dos plat, pousser dans le sol pour soulever la barre.', tips: 'Le mouvement roi. Dos toujours plat, barre contre le corps.', defaultSets: 4, defaultReps: '5', defaultRest: 180 },
  { id: 'bar-04', name: 'Rowing barre Yates', category: 'musculation', equipment: ['barre'], muscles: ['dos'], muscleSecondary: ['biceps', 'epaules'], difficulty: 'intermediaire', description: 'Légèrement penché, barre en pronation, tirer vers le bas du ventre.', defaultSets: 4, defaultReps: '8-10', defaultRest: 90 },
  { id: 'bar-05', name: 'Développé militaire barre', category: 'musculation', equipment: ['barre'], muscles: ['epaules'], muscleSecondary: ['triceps', 'abdominaux'], difficulty: 'intermediaire', description: 'Debout ou assis, barre à hauteur des clavicules, pousser au-dessus de la tête.', defaultSets: 4, defaultReps: '6-10', defaultRest: 90 },
  { id: 'bar-06', name: 'Curl barre EZ', category: 'musculation', equipment: ['barre'], muscles: ['biceps'], muscleSecondary: ['avant_bras'], difficulty: 'debutant', description: 'Barre EZ ou droite, curl complet, coudes fixes le long du corps.', defaultSets: 3, defaultReps: '10-12', defaultRest: 75 },
  { id: 'bar-07', name: 'Front squat', category: 'musculation', equipment: ['barre'], muscles: ['quadriceps'], muscleSecondary: ['abdominaux', 'epaules'], difficulty: 'avance', description: 'Barre en position avant (sur les deltoïdes), squat profond, tronc très vertical.', defaultSets: 4, defaultReps: '6-8', defaultRest: 120 },

  // ── MACHINES ─────────────────────────────────────────────────────────────

  { id: 'mach-01', name: 'Presse à cuisses', category: 'musculation', equipment: ['machine'], muscles: ['quadriceps'], muscleSecondary: ['fessiers', 'ischio_jambiers'], difficulty: 'debutant', description: 'Assis, pieds sur la plateforme, pousser en étendant les jambes sans verrouiller les genoux.', tips: 'Plus les pieds sont hauts, plus les fessiers travaillent.', defaultSets: 4, defaultReps: '10-15', defaultRest: 90 },
  { id: 'mach-02', name: 'Leg curl couché', category: 'musculation', equipment: ['machine'], muscles: ['ischio_jambiers'], difficulty: 'debutant', description: 'Allongé face vers le bas, fléchir les jambes vers les fessiers.', defaultSets: 3, defaultReps: '12-15', defaultRest: 75 },
  { id: 'mach-03', name: 'Leg extension', category: 'musculation', equipment: ['machine'], muscles: ['quadriceps'], difficulty: 'debutant', description: 'Assis, étendre les jambes complètement, contrôle sur la descente.', tips: 'Déconseillé si problème de genou. Contrôle excentrique important.', defaultSets: 3, defaultReps: '12-15', defaultRest: 75 },
  { id: 'mach-04', name: 'Tirage vertical (Lat pulldown)', category: 'musculation', equipment: ['machine'], muscles: ['dos'], muscleSecondary: ['biceps'], difficulty: 'debutant', description: 'Prise large, tirer la barre vers le sternum en écartant les coudes.', defaultSets: 4, defaultReps: '10-12', defaultRest: 75 },
  { id: 'mach-05', name: 'Rowing poulie basse', category: 'musculation', equipment: ['machine'], muscles: ['dos'], muscleSecondary: ['biceps', 'epaules'], difficulty: 'debutant', description: 'Assis, tirer la poignée vers le ventre, coudes tirés en arrière, dos droit.', defaultSets: 4, defaultReps: '10-12', defaultRest: 75 },
  { id: 'mach-06', name: 'Développé épaules machine', category: 'musculation', equipment: ['machine'], muscles: ['epaules'], muscleSecondary: ['triceps'], difficulty: 'debutant', description: 'Pousser les poignées vers le haut, bonne alternative pour débutants ou lombalgiques.', defaultSets: 3, defaultReps: '12', defaultRest: 75 },
  { id: 'mach-07', name: 'Chest press machine', category: 'musculation', equipment: ['machine'], muscles: ['pectoraux'], muscleSecondary: ['triceps', 'epaules'], difficulty: 'debutant', description: 'Pousser les poignées devant soi, bon pour apprendre le mouvement de poussée.', defaultSets: 3, defaultReps: '12-15', defaultRest: 75 },
  { id: 'mach-08', name: 'Pec deck (butterfly)', category: 'musculation', equipment: ['machine'], muscles: ['pectoraux'], difficulty: 'debutant', description: 'Ramener les coudes l\'un vers l\'autre devant la poitrine, étirement maximal en arrière.', defaultSets: 3, defaultReps: '15', defaultRest: 60 },
  { id: 'mach-09', name: 'Extension triceps poulie haute', category: 'musculation', equipment: ['machine'], muscles: ['triceps'], difficulty: 'debutant', description: 'Poulie haute, corde ou barre, extension des bras vers le bas, coudes fixes.', defaultSets: 3, defaultReps: '12-15', defaultRest: 60 },
  { id: 'mach-10', name: 'Curl poulie basse', category: 'musculation', equipment: ['machine'], muscles: ['biceps'], difficulty: 'debutant', description: 'Poulie basse, tirer vers les épaules, tension constante tout au long du mouvement.', defaultSets: 3, defaultReps: '12-15', defaultRest: 60 },
  { id: 'mach-11', name: 'Abducteur (machine)', category: 'musculation', equipment: ['machine'], muscles: ['fessiers'], muscleSecondary: ['ischio_jambiers'], difficulty: 'debutant', description: 'Assis, écarter les cuisses contre la résistance, renforce le moyen fessier.', defaultSets: 3, defaultReps: '15-20', defaultRest: 60 },
  { id: 'mach-12', name: 'Adducteur (machine)', category: 'musculation', equipment: ['machine'], muscles: ['quadriceps'], difficulty: 'debutant', description: 'Assis, rapprocher les cuisses contre la résistance, travaille l\'intérieur des cuisses.', defaultSets: 3, defaultReps: '15-20', defaultRest: 60 },
  { id: 'mach-13', name: 'Élévation mollets machine', category: 'musculation', equipment: ['machine'], muscles: ['mollets'], difficulty: 'debutant', description: 'Debout sur la plateforme, poids sur les épaules, élévation complète des talons.', defaultSets: 4, defaultReps: '20', defaultRest: 45 },

  // ── ÉLASTIQUES ────────────────────────────────────────────────────────────

  { id: 'el-01', name: 'Squat élastique', category: 'musculation', equipment: ['elastique'], muscles: ['quadriceps'], muscleSecondary: ['fessiers'], difficulty: 'debutant', description: 'Élastique sous les pieds et sur les épaules, squat standard avec résistance progressive.', defaultSets: 3, defaultReps: '15', defaultRest: 60 },
  { id: 'el-02', name: 'Kick-back élastique', category: 'musculation', equipment: ['elastique'], muscles: ['fessiers'], difficulty: 'debutant', description: 'À quatre pattes, élastique autour des chevilles, extension d\'une jambe vers l\'arrière.', defaultSets: 3, defaultReps: '15 par jambe', defaultRest: 45 },
  { id: 'el-03', name: 'Band pull-apart', category: 'musculation', equipment: ['elastique'], muscles: ['epaules'], muscleSecondary: ['dos'], difficulty: 'debutant', description: 'Bras tendus devant soi, élastique tenu à deux mains, écarter les bras au maximum.', defaultSets: 3, defaultReps: '20', defaultRest: 45 },
  { id: 'el-04', name: 'Face pull élastique', category: 'musculation', equipment: ['elastique'], muscles: ['epaules'], muscleSecondary: ['dos'], difficulty: 'intermediaire', description: 'Élastique fixé à hauteur du visage, tirer vers le visage en écartant les coudes.', defaultSets: 3, defaultReps: '15', defaultRest: 60 },

  // ── YOGA ──────────────────────────────────────────────────────────────────

  { id: 'yoga-01', name: 'Chien tête en bas (Adho Mukha Svanasana)', category: 'yoga', equipment: ['tapis'], muscles: ['ischio_jambiers'], muscleSecondary: ['epaules', 'mollets'], difficulty: 'debutant', description: 'Corps en V inversé, mains et pieds au sol, dos et bras en ligne droite. Relâche la colonne.', tips: 'Plier légèrement les genoux si les ischio-jambiers sont raides.', defaultSets: 1, defaultDuration: '5-10 respirations', defaultRest: 0 },
  { id: 'yoga-02', name: 'Guerrier I (Virabhadrasana I)', category: 'yoga', equipment: ['tapis'], muscles: ['quadriceps'], muscleSecondary: ['epaules', 'fessiers'], difficulty: 'debutant', description: 'Pied avant fléchi à 90°, pied arrière à 45°, bras levés au-dessus de la tête.', defaultSets: 1, defaultDuration: '5 respirations par côté', defaultRest: 0 },
  { id: 'yoga-03', name: 'Guerrier II (Virabhadrasana II)', category: 'yoga', equipment: ['tapis'], muscles: ['quadriceps'], muscleSecondary: ['epaules', 'ischio_jambiers'], difficulty: 'debutant', description: 'Écart de jambes, genou avant fléchi, bras ouverts sur les côtés, regard sur la main avant.', defaultSets: 1, defaultDuration: '5 respirations par côté', defaultRest: 0 },
  { id: 'yoga-04', name: 'Guerrier III (Virabhadrasana III)', category: 'yoga', equipment: ['tapis'], muscles: ['fessiers'], muscleSecondary: ['ischio_jambiers', 'gainage'], difficulty: 'intermediaire', description: 'Équilibre sur une jambe, corps horizontal, jambe arrière tendue, bras vers l\'avant.', defaultSets: 1, defaultDuration: '5 respirations par côté', defaultRest: 0 },
  { id: 'yoga-05', name: 'Pose de l\'arbre (Vrksasana)', category: 'yoga', equipment: ['tapis'], muscles: ['fessiers'], muscleSecondary: ['gainage', 'mollets'], difficulty: 'debutant', description: 'Équilibre sur une jambe, pied opposé sur la cheville, mollet ou cuisse. Mains en prière.', defaultSets: 1, defaultDuration: '5-10 respirations par côté', defaultRest: 0 },
  { id: 'yoga-06', name: 'Cobra (Bhujangasana)', category: 'yoga', equipment: ['tapis'], muscles: ['dos'], muscleSecondary: ['abdominaux', 'epaules'], difficulty: 'debutant', description: 'À plat ventre, mains sous les épaules, lever le buste en extension du dos.', tips: 'Version douce du chien tête en haut. Ouvre la poitrine.', defaultSets: 1, defaultDuration: '5 respirations', defaultRest: 0 },
  { id: 'yoga-07', name: 'Pose de l\'enfant (Balasana)', category: 'yoga', equipment: ['tapis'], muscles: ['dos'], muscleSecondary: ['epaules', 'ischio_jambiers'], difficulty: 'debutant', description: 'Assis sur les talons, se prosterner en avant, bras tendus. Pose de repos et récupération.', defaultSets: 1, defaultDuration: '10+ respirations', defaultRest: 0 },
  { id: 'yoga-08', name: 'Pigeon (Eka Pada Rajakapotasana)', category: 'yoga', equipment: ['tapis'], muscles: ['fessiers'], muscleSecondary: ['ischio_jambiers', 'quadriceps'], difficulty: 'intermediaire', description: 'Jambe avant pliée au sol, jambe arrière tendue, s\'incliner vers l\'avant. Ouverture profonde des hanches.', tips: 'Ne forcer jamais. Rester dans la pose et respirer profondément.', defaultSets: 1, defaultDuration: '10 respirations par côté', defaultRest: 0 },
  { id: 'yoga-09', name: 'Pont de yoga (Setu Bandha)', category: 'yoga', equipment: ['tapis'], muscles: ['fessiers'], muscleSecondary: ['ischio_jambiers', 'dos'], difficulty: 'debutant', description: 'Sur le dos, pieds à plat, lever les hanches en arc de cercle. Version yoga du pont fessier.', defaultSets: 1, defaultDuration: '5-10 respirations', defaultRest: 0 },
  { id: 'yoga-10', name: 'Chaise (Utkatasana)', category: 'yoga', equipment: ['tapis'], muscles: ['quadriceps'], muscleSecondary: ['fessiers', 'epaules'], difficulty: 'debutant', description: 'Pieds joints ou légèrement écartés, s\'asseoir dans l\'air, bras levés. Renforce les cuisses.', defaultSets: 1, defaultDuration: '5-10 respirations', defaultRest: 0 },
  { id: 'yoga-11', name: 'Triangle (Trikonasana)', category: 'yoga', equipment: ['tapis'], muscles: ['ischio_jambiers'], muscleSecondary: ['obliques', 'epaules'], difficulty: 'debutant', description: 'Écart de jambes, pencher sur le côté, main sur le tibia, autre bras vers le ciel.', defaultSets: 1, defaultDuration: '5 respirations par côté', defaultRest: 0 },
  { id: 'yoga-12', name: 'Fente basse (Anjaneyasana)', category: 'yoga', equipment: ['tapis'], muscles: ['quadriceps'], muscleSecondary: ['fessiers', 'ischio_jambiers'], difficulty: 'debutant', description: 'Fente avant, genou arrière au sol, ouvrir les hanches vers le bas. Étire le psoas.', defaultSets: 1, defaultDuration: '8 respirations par côté', defaultRest: 0 },
  { id: 'yoga-13', name: 'Torsion assise (Ardha Matsyendrasana)', category: 'yoga', equipment: ['tapis'], muscles: ['obliques'], muscleSecondary: ['dos', 'ischio_jambiers'], difficulty: 'debutant', description: 'Assis, une jambe croisée, rotation du buste, bras en butée contre le genou.', defaultSets: 1, defaultDuration: '5 respirations par côté', defaultRest: 0 },
  { id: 'yoga-14', name: 'Demi-lune (Ardha Chandrasana)', category: 'yoga', equipment: ['tapis'], muscles: ['fessiers'], muscleSecondary: ['obliques', 'epaules'], difficulty: 'avance', description: 'Équilibre sur une jambe et une main, corps en étoile ouverte sur le côté.', defaultSets: 1, defaultDuration: '5 respirations par côté', defaultRest: 0 },
  { id: 'yoga-15', name: 'Salutation au soleil (Surya Namaskar)', category: 'yoga', equipment: ['tapis'], muscles: ['corps_entier'], difficulty: 'debutant', description: 'Séquence de 12 postures enchaînées. Réchauffe le corps, étire tous les groupes musculaires.', tips: 'Idéal en début de séance. 3-5 tours pour un bon échauffement.', defaultSets: 1, defaultDuration: '3-5 tours', defaultRest: 0 },
  { id: 'yoga-16', name: 'Pince assise (Paschimottanasana)', category: 'yoga', equipment: ['tapis'], muscles: ['ischio_jambiers'], muscleSecondary: ['dos', 'mollets'], difficulty: 'debutant', description: 'Jambes tendues, se pencher vers les pieds, dos allongé sur les cuisses.', defaultSets: 1, defaultDuration: '10 respirations', defaultRest: 0 },
  { id: 'yoga-17', name: 'Bateau (Navasana)', category: 'yoga', equipment: ['tapis'], muscles: ['abdominaux'], muscleSecondary: ['ischio_jambiers', 'epaules'], difficulty: 'intermediaire', description: 'Assis, jambes levées à 45°, bras parallèles au sol. Maintenir en contractant les abdos.', defaultSets: 1, defaultDuration: '5-10 respirations', defaultRest: 0 },
  { id: 'yoga-18', name: 'Chien tête en haut (Urdhva Mukha Svanasana)', category: 'yoga', equipment: ['tapis'], muscles: ['dos'], muscleSecondary: ['pectoraux', 'epaules'], difficulty: 'intermediaire', description: 'À plat ventre, bras tendus, buste levé, hanches au sol, regard vers le haut.', defaultSets: 1, defaultDuration: '5 respirations', defaultRest: 0 },
  { id: 'yoga-19', name: 'Étoile (Utthita Hasta Padangusthasana)', category: 'yoga', equipment: ['tapis'], muscles: ['fessiers'], muscleSecondary: ['ischio_jambiers', 'gainage'], difficulty: 'avance', description: 'Debout, lever une jambe sur le côté en tenant le pied. Travail d\'équilibre et de souplesse.', defaultSets: 1, defaultDuration: '5 respirations par côté', defaultRest: 0 },
  { id: 'yoga-20', name: 'Lotus (Padmasana)', category: 'yoga', equipment: ['tapis'], muscles: ['ischio_jambiers'], muscleSecondary: ['fessiers'], difficulty: 'avance', description: 'Jambes croisées, pieds sur les cuisses opposées. Posture de méditation profonde.', tips: 'Ne forcer jamais les genoux. Commencer par le demi-lotus.', defaultSets: 1, defaultDuration: '5-20 min', defaultRest: 0 },

  // ── CARDIO / MOBILITÉ ─────────────────────────────────────────────────────

  { id: 'card-01', name: 'Jumping jacks', category: 'cardio', equipment: ['aucun'], muscles: ['corps_entier'], difficulty: 'debutant', description: 'Sauts avec écartement simultané des bras et des jambes. Cardio léger d\'échauffement.', defaultSets: 3, defaultDuration: '30s', defaultRest: 30 },
  { id: 'card-02', name: 'High knees', category: 'cardio', equipment: ['aucun'], muscles: ['quadriceps'], muscleSecondary: ['abdominaux'], difficulty: 'debutant', description: 'Course sur place en levant les genoux à hauteur des hanches, bras en mouvement.', defaultSets: 3, defaultDuration: '30s', defaultRest: 30 },
  { id: 'card-03', name: 'Corde à sauter', category: 'cardio', equipment: ['aucun'], muscles: ['mollets'], muscleSecondary: ['corps_entier'], difficulty: 'debutant', description: 'Cardio efficace, améliore la coordination et l\'endurance. Excellent brûleur de calories.', defaultSets: 3, defaultDuration: '1-3 min', defaultRest: 60 },
  { id: 'card-04', name: 'Box jumps', category: 'cardio', equipment: ['aucun'], muscles: ['quadriceps'], muscleSecondary: ['fessiers', 'mollets'], difficulty: 'intermediaire', description: 'Sauts explosifs sur une boîte ou une surface surélevée, atterrissage contrôlé.', defaultSets: 4, defaultReps: '8', defaultRest: 60 },
  { id: 'card-05', name: 'Roller (mobilité épaules)', category: 'mobilite', equipment: ['tapis'], muscles: ['epaules'], muscleSecondary: ['dos'], difficulty: 'debutant', description: 'Rouler sur le foam roller le long de la colonne, dénouer les tensions dorsales.', defaultSets: 1, defaultDuration: '2-3 min', defaultRest: 0 },
  { id: 'card-06', name: 'Étirement quadriceps debout', category: 'mobilite', equipment: ['aucun'], muscles: ['quadriceps'], difficulty: 'debutant', description: 'Debout, attraper un pied derrière soi et tirer doucement. Garder les genoux alignés.', defaultSets: 1, defaultDuration: '30s par jambe', defaultRest: 0 },
  { id: 'card-07', name: 'Étirement des ischio-jambiers au sol', category: 'mobilite', equipment: ['tapis'], muscles: ['ischio_jambiers'], difficulty: 'debutant', description: 'Sur le dos, lever une jambe tendue et tirer vers soi avec les mains.', defaultSets: 1, defaultDuration: '30s par jambe', defaultRest: 0 },
  { id: 'card-08', name: 'Hip circles (rotation des hanches)', category: 'mobilite', equipment: ['aucun'], muscles: ['fessiers'], muscleSecondary: ['ischio_jambiers'], difficulty: 'debutant', description: 'Debout, mains sur les hanches, grands cercles du bassin. Mobilise les hanches.', defaultSets: 2, defaultReps: '10 par sens', defaultRest: 0 },
  { id: 'card-09', name: 'Cat-Cow (chat-vache)', category: 'mobilite', equipment: ['tapis'], muscles: ['dos'], muscleSecondary: ['abdominaux'], difficulty: 'debutant', description: 'À quatre pattes, alterner flexion et extension de la colonne en synchronisant avec la respiration.', defaultSets: 1, defaultReps: '10 cycles', defaultRest: 0 },
  { id: 'card-10', name: 'World\'s Greatest Stretch', category: 'mobilite', equipment: ['tapis'], muscles: ['corps_entier'], difficulty: 'intermediaire', description: 'Fente avant, rotation du buste, main au ciel. Mobilise hanches, thorax, épaules en un seul mouvement.', tips: 'L\'exercice de mobilité le plus complet. Parfait en échauffement.', defaultSets: 2, defaultReps: '5 par côté', defaultRest: 0 },
];

export const MUSCLE_LABELS: Record<string, string> = {
  pectoraux: 'Pectoraux',
  dos: 'Dos',
  epaules: 'Épaules',
  biceps: 'Biceps',
  triceps: 'Triceps',
  avant_bras: 'Avant-bras',
  abdominaux: 'Abdominaux',
  obliques: 'Obliques',
  quadriceps: 'Quadriceps',
  ischio_jambiers: 'Ischio-jambiers',
  fessiers: 'Fessiers',
  mollets: 'Mollets',
  corps_entier: 'Corps entier',
  gainage: 'Gainage',
};

export const EQUIPMENT_LABELS: Record<string, string> = {
  aucun: 'Poids du corps',
  halteres: 'Haltères',
  barre: 'Barre',
  machine: 'Machine',
  elastique: 'Élastique',
  tapis: 'Tapis',
  barre_traction: 'Barre de traction',
  kettlebell: 'Kettlebell',
  banc: 'Banc',
};

export const EQUIPMENT_COLORS: Record<string, string> = {
  aucun: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
  halteres: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
  barre: 'bg-orange-500/20 text-orange-400 border-orange-500/30',
  machine: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
  elastique: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30',
  tapis: 'bg-teal-500/20 text-teal-400 border-teal-500/30',
  barre_traction: 'bg-red-500/20 text-red-400 border-red-500/30',
  kettlebell: 'bg-amber-500/20 text-amber-400 border-amber-500/30',
  banc: 'bg-slate-500/20 text-slate-400 border-slate-500/30',
};

export const CATEGORY_COLORS: Record<string, string> = {
  musculation: 'from-blue-600 to-indigo-600',
  yoga: 'from-teal-500 to-emerald-600',
  cardio: 'from-orange-500 to-red-500',
  mobilite: 'from-purple-500 to-pink-500',
};

export const DIFFICULTY_COLORS: Record<string, string> = {
  debutant: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20',
  intermediaire: 'text-amber-400 bg-amber-500/10 border-amber-500/20',
  avance: 'text-red-400 bg-red-500/10 border-red-500/20',
};
