import { Coach, Client, Session, Invoice, Payment, ProgressMeasurement, ShopProduct, CoachingPack } from './types';

export const mockCoaches: Coach[] = [
  {
    id: 'coach-1',
    name: 'Marie Dupont',
    email: 'marie.dupont@coachpro.fr',
    role: 'coach',
    speciality: 'Fitness & Musculation',
    iban: 'FR76 3000 6000 0112 3456 7890 189',
    clientIds: ['client-1', 'client-2', 'client-3'],
    phone: '+33 6 12 34 56 78',
    bio: 'Coach certifiée avec 8 ans d\'expérience en fitness et musculation.',
    rating: 4.9,
    sessionPrice: 65,
    createdAt: '2023-01-15',
  },
  {
    id: 'coach-2',
    name: 'Thomas Martin',
    email: 'thomas.martin@coachpro.fr',
    role: 'coach',
    speciality: 'Nutrition & Performance',
    iban: 'FR76 3000 6000 0198 7654 3210 456',
    clientIds: ['client-4', 'client-5', 'client-6'],
    phone: '+33 6 98 76 54 32',
    bio: 'Spécialiste en nutrition sportive et optimisation des performances.',
    rating: 4.7,
    sessionPrice: 70,
    createdAt: '2023-02-20',
  },
  {
    id: 'coach-3',
    name: 'Sophie Bernard',
    email: 'sophie.bernard@coachpro.fr',
    role: 'coach',
    speciality: 'Yoga & Bien-être',
    iban: 'FR76 3000 6000 0145 6789 0123 789',
    clientIds: ['client-7', 'client-8'],
    phone: '+33 6 45 67 89 01',
    bio: 'Professeure de yoga certifiée, spécialisée dans le bien-être holistique.',
    rating: 4.8,
    sessionPrice: 55,
    createdAt: '2023-03-10',
  },
];

export const mockClients: Client[] = [
  {
    id: 'client-1',
    name: 'Lucas Petit',
    email: 'lucas.petit@email.fr',
    role: 'client',
    coachId: 'coach-1',
    phone: '+33 6 11 22 33 44',
    dateOfBirth: '1990-05-15',
    goal: 'Prise de masse musculaire',
    status: 'active',
    address: '12 Rue de la Paix, 75001 Paris',
    startDate: '2024-01-10',
    createdAt: '2024-01-10',
  },
  {
    id: 'client-2',
    name: 'Emma Rousseau',
    email: 'emma.rousseau@email.fr',
    role: 'client',
    coachId: 'coach-1',
    phone: '+33 6 22 33 44 55',
    dateOfBirth: '1995-08-22',
    goal: 'Perte de poids et tonification',
    status: 'active',
    address: '45 Avenue Victor Hugo, 75016 Paris',
    startDate: '2024-02-01',
    createdAt: '2024-02-01',
  },
  {
    id: 'client-3',
    name: 'Pierre Moreau',
    email: 'pierre.moreau@email.fr',
    role: 'client',
    coachId: 'coach-1',
    phone: '+33 6 33 44 55 66',
    dateOfBirth: '1985-12-01',
    goal: 'Amélioration des performances sportives',
    status: 'inactive',
    address: '78 Boulevard Haussmann, 75009 Paris',
    startDate: '2023-11-15',
    createdAt: '2023-11-15',
  },
  {
    id: 'client-4',
    name: 'Chloé Lefevre',
    email: 'chloe.lefevre@email.fr',
    role: 'client',
    coachId: 'coach-2',
    phone: '+33 6 44 55 66 77',
    dateOfBirth: '1992-03-08',
    goal: 'Nutrition pour marathon',
    status: 'active',
    address: '23 Rue du Faubourg Saint-Antoine, 75011 Paris',
    startDate: '2024-01-20',
    createdAt: '2024-01-20',
  },
  {
    id: 'client-5',
    name: 'Antoine Dubois',
    email: 'antoine.dubois@email.fr',
    role: 'client',
    coachId: 'coach-2',
    phone: '+33 6 55 66 77 88',
    dateOfBirth: '1988-07-14',
    goal: 'Optimisation composition corporelle',
    status: 'active',
    address: '56 Rue de Rivoli, 75004 Paris',
    startDate: '2024-03-01',
    createdAt: '2024-03-01',
  },
  {
    id: 'client-6',
    name: 'Camille Vincent',
    email: 'camille.vincent@email.fr',
    role: 'client',
    coachId: 'coach-2',
    phone: '+33 6 66 77 88 99',
    dateOfBirth: '1997-11-30',
    goal: 'Rééquilibrage alimentaire',
    status: 'pending',
    address: '89 Avenue des Champs-Élysées, 75008 Paris',
    startDate: '2024-04-15',
    createdAt: '2024-04-15',
  },
  {
    id: 'client-7',
    name: 'Hugo Garnier',
    email: 'hugo.garnier@email.fr',
    role: 'client',
    coachId: 'coach-3',
    phone: '+33 6 77 88 99 00',
    dateOfBirth: '1993-06-25',
    goal: 'Réduction du stress et flexibilité',
    status: 'active',
    address: '34 Rue de Montmartre, 75002 Paris',
    startDate: '2024-02-10',
    createdAt: '2024-02-10',
  },
  {
    id: 'client-8',
    name: 'Léa Simon',
    email: 'lea.simon@email.fr',
    role: 'client',
    coachId: 'coach-3',
    phone: '+33 6 88 99 00 11',
    dateOfBirth: '1999-09-18',
    goal: 'Bien-être général et méditation',
    status: 'active',
    address: '67 Rue Saint-Denis, 75001 Paris',
    startDate: '2024-03-20',
    createdAt: '2024-03-20',
  },
];

export const mockSessions: Session[] = [
  {
    id: 'session-1',
    coachId: 'coach-1',
    clientId: 'client-1',
    date: '2026-05-12',
    startTime: '09:00',
    endTime: '10:00',
    type: 'individual',
    status: 'completed',
    location: 'Salle de sport Paris 1er',
    price: 65,
    notes: 'Excellent progrès sur les squats',
  },
  {
    id: 'session-2',
    coachId: 'coach-1',
    clientId: 'client-2',
    date: '2026-05-12',
    startTime: '11:00',
    endTime: '12:00',
    type: 'individual',
    status: 'completed',
    location: 'Salle de sport Paris 1er',
    price: 65,
  },
  {
    id: 'session-3',
    coachId: 'coach-1',
    clientId: 'client-1',
    date: '2026-05-14',
    startTime: '14:00',
    endTime: '15:00',
    type: 'individual',
    status: 'completed',
    location: 'Salle de sport Paris 1er',
    price: 65,
  },
  {
    id: 'session-4',
    coachId: 'coach-1',
    clientId: 'client-2',
    date: '2026-05-19',
    startTime: '09:00',
    endTime: '10:00',
    type: 'individual',
    status: 'scheduled',
    location: 'Salle de sport Paris 1er',
    price: 65,
  },
  {
    id: 'session-5',
    coachId: 'coach-1',
    clientId: 'client-1',
    date: '2026-05-19',
    startTime: '10:30',
    endTime: '11:30',
    type: 'individual',
    status: 'scheduled',
    location: 'Salle de sport Paris 1er',
    price: 65,
  },
  {
    id: 'session-6',
    coachId: 'coach-1',
    clientId: 'client-3',
    date: '2026-05-20',
    startTime: '16:00',
    endTime: '17:00',
    type: 'individual',
    status: 'scheduled',
    location: 'En ligne',
    price: 65,
  },
  {
    id: 'session-7',
    coachId: 'coach-2',
    clientId: 'client-4',
    date: '2026-05-13',
    startTime: '08:00',
    endTime: '09:00',
    type: 'individual',
    status: 'completed',
    location: 'Cabinet nutritionnel',
    price: 70,
  },
  {
    id: 'session-8',
    coachId: 'coach-2',
    clientId: 'client-5',
    date: '2026-05-13',
    startTime: '10:00',
    endTime: '11:00',
    type: 'individual',
    status: 'completed',
    location: 'Cabinet nutritionnel',
    price: 70,
  },
  {
    id: 'session-9',
    coachId: 'coach-2',
    clientId: 'client-4',
    date: '2026-05-20',
    startTime: '08:00',
    endTime: '09:00',
    type: 'individual',
    status: 'scheduled',
    location: 'Cabinet nutritionnel',
    price: 70,
  },
  {
    id: 'session-10',
    coachId: 'coach-2',
    clientId: 'client-5',
    date: '2026-05-21',
    startTime: '10:00',
    endTime: '11:00',
    type: 'individual',
    status: 'scheduled',
    location: 'Cabinet nutritionnel',
    price: 70,
  },
  {
    id: 'session-11',
    coachId: 'coach-3',
    clientId: 'client-7',
    date: '2026-05-15',
    startTime: '07:00',
    endTime: '08:00',
    type: 'individual',
    status: 'completed',
    location: 'Studio yoga',
    price: 55,
  },
  {
    id: 'session-12',
    coachId: 'coach-3',
    clientId: 'client-8',
    date: '2026-05-15',
    startTime: '09:00',
    endTime: '10:30',
    type: 'group',
    status: 'completed',
    location: 'Studio yoga',
    price: 55,
  },
  {
    id: 'session-13',
    coachId: 'coach-3',
    clientId: 'client-7',
    date: '2026-05-22',
    startTime: '07:00',
    endTime: '08:00',
    type: 'individual',
    status: 'scheduled',
    location: 'Studio yoga',
    price: 55,
  },
  {
    id: 'session-14',
    coachId: 'coach-1',
    clientId: 'client-1',
    date: '2026-05-08',
    startTime: '09:00',
    endTime: '10:00',
    type: 'individual',
    status: 'completed',
    location: 'Salle de sport Paris 1er',
    price: 65,
  },
  {
    id: 'session-15',
    coachId: 'coach-1',
    clientId: 'client-2',
    date: '2026-05-08',
    startTime: '11:00',
    endTime: '12:00',
    type: 'individual',
    status: 'completed',
    location: 'Salle de sport Paris 1er',
    price: 65,
  },
  {
    id: 'session-16',
    coachId: 'coach-2',
    clientId: 'client-6',
    date: '2026-05-21',
    startTime: '14:00',
    endTime: '15:00',
    type: 'individual',
    status: 'scheduled',
    location: 'En ligne',
    price: 70,
  },
  {
    id: 'session-17',
    coachId: 'coach-3',
    clientId: 'client-8',
    date: '2026-05-22',
    startTime: '09:00',
    endTime: '10:30',
    type: 'group',
    status: 'scheduled',
    location: 'Studio yoga',
    price: 55,
  },
  {
    id: 'session-18',
    coachId: 'coach-1',
    clientId: 'client-3',
    date: '2026-05-09',
    startTime: '15:00',
    endTime: '16:00',
    type: 'individual',
    status: 'no_show',
    location: 'Salle de sport Paris 1er',
    price: 65,
  },
  {
    id: 'session-19',
    coachId: 'coach-2',
    clientId: 'client-4',
    date: '2026-05-06',
    startTime: '08:00',
    endTime: '09:00',
    type: 'individual',
    status: 'completed',
    location: 'Cabinet nutritionnel',
    price: 70,
  },
  {
    id: 'session-20',
    coachId: 'coach-3',
    clientId: 'client-7',
    date: '2026-05-08',
    startTime: '07:00',
    endTime: '08:00',
    type: 'individual',
    status: 'completed',
    location: 'Studio yoga',
    price: 55,
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'invoice-1',
    number: 'FAC-2026-001',
    coachId: 'coach-1',
    clientId: 'client-1',
    clientName: 'Lucas Petit',
    items: [
      { id: 'item-1', description: 'Séances de coaching (4x)', quantity: 4, unitPrice: 65, total: 260 },
    ],
    subtotal: 260,
    tax: 0,
    total: 260,
    status: 'paid',
    issueDate: '2026-04-01',
    dueDate: '2026-04-15',
    paidDate: '2026-04-10',
  },
  {
    id: 'invoice-2',
    number: 'FAC-2026-002',
    coachId: 'coach-1',
    clientId: 'client-2',
    clientName: 'Emma Rousseau',
    items: [
      { id: 'item-2', description: 'Séances de coaching (4x)', quantity: 4, unitPrice: 65, total: 260 },
    ],
    subtotal: 260,
    tax: 0,
    total: 260,
    status: 'sent',
    issueDate: '2026-05-01',
    dueDate: '2026-05-15',
  },
  {
    id: 'invoice-3',
    number: 'FAC-2026-003',
    coachId: 'coach-1',
    clientId: 'client-3',
    clientName: 'Pierre Moreau',
    items: [
      { id: 'item-3', description: 'Séances de coaching (2x)', quantity: 2, unitPrice: 65, total: 130 },
    ],
    subtotal: 130,
    tax: 0,
    total: 130,
    status: 'overdue',
    issueDate: '2026-04-01',
    dueDate: '2026-04-20',
  },
  {
    id: 'invoice-4',
    number: 'FAC-2026-004',
    coachId: 'coach-2',
    clientId: 'client-4',
    clientName: 'Chloé Lefevre',
    items: [
      { id: 'item-4', description: 'Consultation nutrition + suivi (4x)', quantity: 4, unitPrice: 70, total: 280 },
    ],
    subtotal: 280,
    tax: 0,
    total: 280,
    status: 'paid',
    issueDate: '2026-04-05',
    dueDate: '2026-04-20',
    paidDate: '2026-04-18',
  },
  {
    id: 'invoice-5',
    number: 'FAC-2026-005',
    coachId: 'coach-2',
    clientId: 'client-5',
    clientName: 'Antoine Dubois',
    items: [
      { id: 'item-5', description: 'Programme nutrition personnalisé', quantity: 1, unitPrice: 150, total: 150 },
      { id: 'item-6', description: 'Séances de suivi (3x)', quantity: 3, unitPrice: 70, total: 210 },
    ],
    subtotal: 360,
    tax: 0,
    total: 360,
    status: 'sent',
    issueDate: '2026-05-01',
    dueDate: '2026-05-20',
  },
  {
    id: 'invoice-6',
    number: 'FAC-2026-006',
    coachId: 'coach-3',
    clientId: 'client-7',
    clientName: 'Hugo Garnier',
    items: [
      { id: 'item-7', description: 'Cours de yoga individuels (4x)', quantity: 4, unitPrice: 55, total: 220 },
    ],
    subtotal: 220,
    tax: 0,
    total: 220,
    status: 'paid',
    issueDate: '2026-04-10',
    dueDate: '2026-04-25',
    paidDate: '2026-04-22',
  },
  {
    id: 'invoice-7',
    number: 'FAC-2026-007',
    coachId: 'coach-3',
    clientId: 'client-8',
    clientName: 'Léa Simon',
    items: [
      { id: 'item-8', description: 'Cours de yoga groupe (4x)', quantity: 4, unitPrice: 55, total: 220 },
    ],
    subtotal: 220,
    tax: 0,
    total: 220,
    status: 'draft',
    issueDate: '2026-05-10',
    dueDate: '2026-05-25',
  },
  {
    id: 'invoice-8',
    number: 'FAC-2026-008',
    coachId: 'coach-1',
    clientId: 'client-1',
    clientName: 'Lucas Petit',
    items: [
      { id: 'item-9', description: 'Séances de coaching (4x)', quantity: 4, unitPrice: 65, total: 260 },
    ],
    subtotal: 260,
    tax: 0,
    total: 260,
    status: 'draft',
    issueDate: '2026-05-15',
    dueDate: '2026-05-30',
  },
  {
    id: 'invoice-9',
    number: 'FAC-2026-009',
    coachId: 'coach-2',
    clientId: 'client-6',
    clientName: 'Camille Vincent',
    items: [
      { id: 'item-10', description: 'Bilan nutritionnel initial', quantity: 1, unitPrice: 120, total: 120 },
    ],
    subtotal: 120,
    tax: 0,
    total: 120,
    status: 'sent',
    issueDate: '2026-05-05',
    dueDate: '2026-05-20',
  },
  {
    id: 'invoice-10',
    number: 'FAC-2026-010',
    coachId: 'coach-1',
    clientId: 'client-2',
    clientName: 'Emma Rousseau',
    items: [
      { id: 'item-11', description: 'Séances de coaching (4x)', quantity: 4, unitPrice: 65, total: 260 },
    ],
    subtotal: 260,
    tax: 0,
    total: 260,
    status: 'paid',
    issueDate: '2026-03-01',
    dueDate: '2026-03-15',
    paidDate: '2026-03-12',
  },
];

export const mockPayments: Payment[] = [
  {
    id: 'payment-1',
    invoiceId: 'invoice-1',
    clientId: 'client-1',
    coachId: 'coach-1',
    amount: 260,
    date: '2026-04-10',
    method: 'bank_transfer',
    status: 'completed',
    reference: 'VIR-20260410-001',
  },
  {
    id: 'payment-2',
    invoiceId: 'invoice-4',
    clientId: 'client-4',
    coachId: 'coach-2',
    amount: 280,
    date: '2026-04-18',
    method: 'card',
    status: 'completed',
    reference: 'CB-20260418-004',
  },
  {
    id: 'payment-3',
    invoiceId: 'invoice-6',
    clientId: 'client-7',
    coachId: 'coach-3',
    amount: 220,
    date: '2026-04-22',
    method: 'bank_transfer',
    status: 'completed',
    reference: 'VIR-20260422-006',
  },
  {
    id: 'payment-4',
    invoiceId: 'invoice-10',
    clientId: 'client-2',
    coachId: 'coach-1',
    amount: 260,
    date: '2026-03-12',
    method: 'bank_transfer',
    status: 'completed',
    reference: 'VIR-20260312-010',
  },
  {
    id: 'payment-5',
    invoiceId: 'invoice-2',
    clientId: 'client-2',
    coachId: 'coach-1',
    amount: 260,
    date: '2026-05-10',
    method: 'bank_transfer',
    status: 'pending',
    reference: 'VIR-20260510-002',
  },
];

// Generate 6 months of progress data for clients
export const mockProgressData: ProgressMeasurement[] = [
  // Client 1 - Lucas Petit (6 months)
  {
    id: 'progress-1-1',
    clientId: 'client-1',
    date: '2025-11-15',
    weight: 85.5,
    bodyFat: 18.2,
    chest: 98,
    waist: 88,
    hips: 95,
    biceps: 35,
    thighs: 58,
  },
  {
    id: 'progress-1-2',
    clientId: 'client-1',
    date: '2025-12-15',
    weight: 86.2,
    bodyFat: 17.8,
    chest: 99,
    waist: 87,
    hips: 95,
    biceps: 35.5,
    thighs: 58.5,
  },
  {
    id: 'progress-1-3',
    clientId: 'client-1',
    date: '2026-01-15',
    weight: 87.0,
    bodyFat: 17.2,
    chest: 100,
    waist: 86,
    hips: 94,
    biceps: 36,
    thighs: 59,
  },
  {
    id: 'progress-1-4',
    clientId: 'client-1',
    date: '2026-02-15',
    weight: 87.8,
    bodyFat: 16.5,
    chest: 101,
    waist: 85,
    hips: 94,
    biceps: 36.5,
    thighs: 59.5,
  },
  {
    id: 'progress-1-5',
    clientId: 'client-1',
    date: '2026-03-15',
    weight: 88.5,
    bodyFat: 15.8,
    chest: 102,
    waist: 84,
    hips: 93,
    biceps: 37,
    thighs: 60,
  },
  {
    id: 'progress-1-6',
    clientId: 'client-1',
    date: '2026-04-15',
    weight: 89.2,
    bodyFat: 15.2,
    chest: 103,
    waist: 83,
    hips: 93,
    biceps: 37.5,
    thighs: 61,
  },
  // Client 2 - Emma Rousseau (6 months)
  {
    id: 'progress-2-1',
    clientId: 'client-2',
    date: '2025-11-15',
    weight: 68.0,
    bodyFat: 28.5,
    chest: 90,
    waist: 76,
    hips: 102,
    biceps: 28,
    thighs: 58,
  },
  {
    id: 'progress-2-2',
    clientId: 'client-2',
    date: '2025-12-15',
    weight: 67.2,
    bodyFat: 27.8,
    chest: 89,
    waist: 75,
    hips: 101,
    biceps: 28,
    thighs: 57.5,
  },
  {
    id: 'progress-2-3',
    clientId: 'client-2',
    date: '2026-01-15',
    weight: 66.5,
    bodyFat: 27.0,
    chest: 89,
    waist: 74,
    hips: 100,
    biceps: 28.5,
    thighs: 57,
  },
  {
    id: 'progress-2-4',
    clientId: 'client-2',
    date: '2026-02-15',
    weight: 65.8,
    bodyFat: 26.2,
    chest: 88,
    waist: 73,
    hips: 99,
    biceps: 28.5,
    thighs: 56.5,
  },
  {
    id: 'progress-2-5',
    clientId: 'client-2',
    date: '2026-03-15',
    weight: 65.0,
    bodyFat: 25.5,
    chest: 88,
    waist: 72,
    hips: 98,
    biceps: 29,
    thighs: 56,
  },
  {
    id: 'progress-2-6',
    clientId: 'client-2',
    date: '2026-04-15',
    weight: 64.3,
    bodyFat: 24.8,
    chest: 87,
    waist: 71,
    hips: 97,
    biceps: 29,
    thighs: 55.5,
  },
  // Client 4 - Chloé Lefevre (6 months)
  {
    id: 'progress-4-1',
    clientId: 'client-4',
    date: '2025-11-15',
    weight: 62.0,
    bodyFat: 22.0,
    chest: 85,
    waist: 68,
    hips: 94,
    biceps: 26,
    thighs: 54,
  },
  {
    id: 'progress-4-2',
    clientId: 'client-4',
    date: '2025-12-15',
    weight: 61.5,
    bodyFat: 21.5,
    chest: 85,
    waist: 67.5,
    hips: 93.5,
    biceps: 26.2,
    thighs: 53.5,
  },
  {
    id: 'progress-4-3',
    clientId: 'client-4',
    date: '2026-01-15',
    weight: 61.0,
    bodyFat: 21.0,
    chest: 84.5,
    waist: 67,
    hips: 93,
    biceps: 26.5,
    thighs: 53,
  },
  {
    id: 'progress-4-4',
    clientId: 'client-4',
    date: '2026-02-15',
    weight: 60.5,
    bodyFat: 20.5,
    chest: 84,
    waist: 66.5,
    hips: 92.5,
    biceps: 26.5,
    thighs: 52.5,
  },
  {
    id: 'progress-4-5',
    clientId: 'client-4',
    date: '2026-03-15',
    weight: 60.0,
    bodyFat: 20.0,
    chest: 84,
    waist: 66,
    hips: 92,
    biceps: 27,
    thighs: 52,
  },
  {
    id: 'progress-4-6',
    clientId: 'client-4',
    date: '2026-04-15',
    weight: 59.5,
    bodyFat: 19.5,
    chest: 83.5,
    waist: 65.5,
    hips: 91.5,
    biceps: 27,
    thighs: 51.5,
  },
  // Client 7 - Hugo Garnier (6 months)
  {
    id: 'progress-7-1',
    clientId: 'client-7',
    date: '2025-11-15',
    weight: 78.0,
    bodyFat: 19.0,
    chest: 96,
    waist: 84,
    hips: 98,
    biceps: 33,
    thighs: 56,
  },
  {
    id: 'progress-7-2',
    clientId: 'client-7',
    date: '2025-12-15',
    weight: 77.5,
    bodyFat: 18.5,
    chest: 96,
    waist: 83.5,
    hips: 97.5,
    biceps: 33,
    thighs: 55.5,
  },
  {
    id: 'progress-7-3',
    clientId: 'client-7',
    date: '2026-01-15',
    weight: 77.0,
    bodyFat: 18.0,
    chest: 95.5,
    waist: 83,
    hips: 97,
    biceps: 33.5,
    thighs: 55,
  },
  {
    id: 'progress-7-4',
    clientId: 'client-7',
    date: '2026-02-15',
    weight: 76.5,
    bodyFat: 17.5,
    chest: 95,
    waist: 82.5,
    hips: 96.5,
    biceps: 33.5,
    thighs: 54.5,
  },
  {
    id: 'progress-7-5',
    clientId: 'client-7',
    date: '2026-03-15',
    weight: 76.0,
    bodyFat: 17.0,
    chest: 95,
    waist: 82,
    hips: 96,
    biceps: 34,
    thighs: 54,
  },
  {
    id: 'progress-7-6',
    clientId: 'client-7',
    date: '2026-04-15',
    weight: 75.5,
    bodyFat: 16.5,
    chest: 94.5,
    waist: 81.5,
    hips: 95.5,
    biceps: 34,
    thighs: 53.5,
  },
];

// ─── Boutique ────────────────────────────────────────────────────────────────

export const mockShopProducts: ShopProduct[] = [
  // Ensembles
  {
    id: 'af-ensemble-1',
    name: 'Ensemble Aries Power',
    description: 'Top brassière + legging taille haute – tissu compressif et respirant, maintien optimal.',
    price: 89,
    originalPrice: 109,
    category: 'ensemble',
    imageColor: 'from-purple-600 to-pink-500',
    badge: 'Best-seller',
    brand: 'ariesfitwear',
    externalUrl: 'https://ariesfitwear.com',
    variants: [
      { color: 'Noir', colorHex: '#1a1a2e', stock: { XS: 5, S: 8, M: 10, L: 6, XL: 4, XXL: 2 } },
      { color: 'Violet', colorHex: '#7c3aed', stock: { XS: 3, S: 6, M: 8, L: 5, XL: 3, XXL: 1 } },
      { color: 'Rose', colorHex: '#ec4899', stock: { XS: 4, S: 7, M: 9, L: 5, XL: 2, XXL: 0 } },
    ],
  },
  {
    id: 'af-ensemble-2',
    name: 'Ensemble Aries Sculpt',
    description: 'Legging sculptant + top dos nu – effet push-up et galbe parfait pour vos entraînements.',
    price: 79,
    category: 'ensemble',
    imageColor: 'from-blue-600 to-cyan-400',
    badge: 'Nouveau',
    brand: 'ariesfitwear',
    externalUrl: 'https://ariesfitwear.com',
    variants: [
      { color: 'Marine', colorHex: '#1e3a5f', stock: { XS: 6, S: 9, M: 11, L: 7, XL: 4, XXL: 2 } },
      { color: 'Bleu glacier', colorHex: '#38bdf8', stock: { XS: 3, S: 5, M: 7, L: 4, XL: 2, XXL: 1 } },
    ],
  },
  {
    id: 'af-ensemble-3',
    name: 'Ensemble Aries Elite',
    description: 'Short de sport + brassière haute performance – idéal running et HIIT.',
    price: 69,
    category: 'ensemble',
    imageColor: 'from-emerald-600 to-teal-400',
    brand: 'ariesfitwear',
    externalUrl: 'https://ariesfitwear.com',
    variants: [
      { color: 'Vert forêt', colorHex: '#065f46', stock: { XS: 4, S: 7, M: 9, L: 6, XL: 3, XXL: 1 } },
      { color: 'Menthe', colorHex: '#6ee7b7', stock: { XS: 3, S: 5, M: 6, L: 4, XL: 2, XXL: 0 } },
    ],
  },
  // Hauts
  {
    id: 'af-top-1',
    name: 'Brassière Aries Flow',
    description: 'Soutien-gorge de sport maintien moyen, bonnets intégrés, tissu sans coutures.',
    price: 39,
    category: 'haut',
    imageColor: 'from-rose-500 to-pink-600',
    brand: 'ariesfitwear',
    externalUrl: 'https://ariesfitwear.com',
    variants: [
      { color: 'Noir', colorHex: '#1a1a2e', stock: { XS: 8, S: 12, M: 15, L: 10, XL: 6, XXL: 3 } },
      { color: 'Nude', colorHex: '#d4a690', stock: { XS: 5, S: 8, M: 10, L: 7, XL: 4, XXL: 2 } },
      { color: 'Rose bonbon', colorHex: '#f472b6', stock: { XS: 4, S: 7, M: 9, L: 5, XL: 3, XXL: 1 } },
    ],
  },
  {
    id: 'af-top-2',
    name: 'Crop Top Aries Dry-Fit',
    description: 'Top court à manches courtes – technologie dry-fit pour une transpiration maîtrisée.',
    price: 34,
    category: 'haut',
    imageColor: 'from-orange-500 to-amber-400',
    badge: 'Nouveau',
    brand: 'ariesfitwear',
    externalUrl: 'https://ariesfitwear.com',
    variants: [
      { color: 'Orange feu', colorHex: '#f97316', stock: { XS: 6, S: 9, M: 11, L: 7, XL: 4, XXL: 2 } },
      { color: 'Blanc', colorHex: '#f8fafc', stock: { XS: 7, S: 10, M: 13, L: 8, XL: 5, XXL: 2 } },
    ],
  },
  // Bas
  {
    id: 'af-legging-1',
    name: 'Legging Aries Push-Up',
    description: 'Legging taille haute avec couture sculptante, effet push-up garanti.',
    price: 59,
    originalPrice: 75,
    category: 'bas',
    imageColor: 'from-violet-700 to-indigo-500',
    badge: 'Promo',
    brand: 'ariesfitwear',
    externalUrl: 'https://ariesfitwear.com',
    variants: [
      { color: 'Noir', colorHex: '#1a1a2e', stock: { XS: 10, S: 14, M: 16, L: 11, XL: 7, XXL: 4 } },
      { color: 'Violet nuit', colorHex: '#4c1d95', stock: { XS: 5, S: 8, M: 10, L: 6, XL: 3, XXL: 1 } },
      { color: 'Bordeaux', colorHex: '#881337', stock: { XS: 4, S: 6, M: 8, L: 5, XL: 2, XXL: 1 } },
    ],
  },
  {
    id: 'af-short-1',
    name: 'Short Aries Speed',
    description: 'Short de sport ultra-léger, doublure intégrée, poche zippée latérale.',
    price: 45,
    category: 'bas',
    imageColor: 'from-sky-500 to-blue-600',
    brand: 'ariesfitwear',
    externalUrl: 'https://ariesfitwear.com',
    variants: [
      { color: 'Noir', colorHex: '#1a1a2e', stock: { XS: 8, S: 12, M: 14, L: 9, XL: 5, XXL: 3 } },
      { color: 'Bleu cobalt', colorHex: '#2563eb', stock: { XS: 4, S: 7, M: 9, L: 6, XL: 3, XXL: 1 } },
    ],
  },
  // Accessoires
  {
    id: 'af-acc-1',
    name: 'Gourde Aries 750ml',
    description: 'Gourde isotherme en inox, maintien chaud/froid 12h, couvercle anti-fuite.',
    price: 29,
    category: 'accessoire',
    imageColor: 'from-slate-600 to-slate-400',
    brand: 'ariesfitwear',
    externalUrl: 'https://ariesfitwear.com',
  },
  {
    id: 'af-acc-2',
    name: 'Résistance Loop Band Set',
    description: 'Set de 5 bandes de résistance latex, niveaux de résistance progressifs.',
    price: 24,
    category: 'accessoire',
    imageColor: 'from-lime-500 to-green-600',
    brand: 'ariesfitwear',
    externalUrl: 'https://ariesfitwear.com',
  },
];

export const mockCoachingPacks: CoachingPack[] = [
  {
    id: 'pack-starter',
    name: 'Pack Starter',
    description: 'Idéal pour débuter votre transformation physique avec un accompagnement professionnel.',
    sessions: 5,
    sessionType: 'présentiel',
    includesDiet: false,
    price: 299,
    priceWithDiet: 399,
    durationWeeks: 5,
    features: [
      '5 séances individuelles en présentiel (1h)',
      'Bilan morphologique initial',
      'Programme d\'entraînement personnalisé',
      'Suivi des performances',
      'Accès à l\'espace client CoachPro',
    ],
    dietDetails: 'Plan nutrition sur-mesure + 3 consultations diététique',
  },
  {
    id: 'pack-essentiel',
    name: 'Pack Essentiel',
    description: 'Le pack le plus populaire pour des résultats durables et une vraie progression.',
    sessions: 10,
    sessionType: 'présentiel',
    includesDiet: false,
    price: 549,
    priceWithDiet: 699,
    durationWeeks: 10,
    badge: 'Populaire',
    popular: true,
    features: [
      '10 séances individuelles en présentiel (1h)',
      'Bilan morphologique + photos de suivi',
      'Programme d\'entraînement évolutif',
      'Suivi hebdomadaire des mensurations',
      'Accès premium CoachPro (graphiques progression)',
      'Support WhatsApp entre les séances',
    ],
    dietDetails: 'Plan nutrition complet + 5 consultations + journaling alimentaire',
  },
  {
    id: 'pack-premium',
    name: 'Pack Premium',
    description: 'Transformation totale sur 3 mois avec suivi nutrition intégré et coaching illimité.',
    sessions: 20,
    sessionType: 'présentiel',
    includesDiet: false,
    price: 999,
    priceWithDiet: 1299,
    durationWeeks: 12,
    badge: 'Meilleur rapport',
    features: [
      '20 séances individuelles en présentiel (1h)',
      'Bilan complet : morphologique + force + cardio',
      'Programme d\'entraînement 3 phases évolutives',
      'Suivi mensurationss bi-mensuel + photos',
      'Accès premium CoachPro',
      'Support illimité WhatsApp',
      'Séance débrief fin de pack offerte',
    ],
    dietDetails: 'Nutrition complète : plan + 8 consultations + suivi macro hebdomadaire',
  },
  {
    id: 'pack-online-starter',
    name: 'Pack Online Starter',
    description: 'Coaching à distance, où que vous soyez. Séances vidéo avec votre coach personnel.',
    sessions: 5,
    sessionType: 'en ligne',
    includesDiet: false,
    price: 249,
    priceWithDiet: 349,
    durationWeeks: 5,
    features: [
      '5 séances vidéo individuelles (1h)',
      'Bilan en visio + questionnaire détaillé',
      'Programme d\'entraînement home/salle',
      'Suivi sur l\'espace client CoachPro',
      'Support email entre les séances',
    ],
    dietDetails: 'Plan nutrition adapté + 2 consultations en visio',
  },
  {
    id: 'pack-online-premium',
    name: 'Pack Online Premium',
    description: 'Coaching en ligne haute intensité avec suivi rapproché et programme complet.',
    sessions: 10,
    sessionType: 'en ligne',
    includesDiet: false,
    price: 449,
    priceWithDiet: 599,
    durationWeeks: 10,
    popular: true,
    features: [
      '10 séances vidéo individuelles (1h)',
      'Programme entraînement personnalisé',
      'Bibliothèque exercices vidéo privée',
      'Suivi progression sur CoachPro',
      'Ajustements programme à mi-parcours',
      'Support WhatsApp illimité',
    ],
    dietDetails: 'Nutrition complète + 5 consultations visio + plan de repas hebdomadaire',
  },
  {
    id: 'pack-elite',
    name: 'Pack Elite',
    description: 'L\'accompagnement ultime : présentiel + en ligne, nutrition, et suivi quotidien sur 3 mois.',
    sessions: 24,
    sessionType: 'mixte',
    includesDiet: true,
    price: 1599,
    durationWeeks: 12,
    badge: 'Exclusif',
    features: [
      '12 séances présentiel + 12 séances vidéo',
      'Analyse corporelle complète (impédancemètre)',
      'Programme d\'entraînement sur-mesure 4 phases',
      'Plan nutrition 100% personnalisé inclus',
      '8 consultations diététique incluses',
      'Suivi quotidien sur CoachPro',
      'Photos et graphiques de progression',
      'Accès groupe VIP coaches',
    ],
  },
];
